language: go

go:
  - "1.16"

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -coverpkg=./problems ./test

after_success:
  - bash <(curl -s https://codecov.io/bash)